name: Listar Hojas Google Sheets

on:
  workflow_dispatch:

jobs:
  listar-hojas:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: pip install -r requirements.txt
        
    - name: Listar Hojas Disponibles
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: |
        cd src
        python -c "
import os
from google_sheets_uploader import GoogleSheetsUploader

# Inicializar conexión
gs_handler = GoogleSheetsUploader(
    credentials_json_string=os.getenv('GOOGLE_CREDENTIALS_JSON'),
    sheet_id=os.getenv('GOOGLE_SHEET_ID')
)

# Listar todas las hojas
spreadsheet = gs_handler.client.open_by_key(os.getenv('GOOGLE_SHEET_ID'))
hojas = [ws.title for ws in spreadsheet.worksheets()]

print('=== HOJAS DISPONIBLES ===')
for hoja in hojas:
    print(f'  - {hoja}')

print(f'\\nTotal: {len(hojas)} hojas')

# Buscar hojas SCR
hojas_scr = [h for h in hojas if h.startswith('SCR')]
print(f'\\n=== HOJAS SCRAPER ===')
for hoja in hojas_scr:
    print(f'  - {hoja}')
"
